name: travel_rs
description: Turismo Rio Grande do Sul.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: ^0.2.7
  cloud_firestore: ^0.12.7
  carousel_pro: ^0.0.13
  scoped_model: ^1.0.1
  firebase_auth: ^0.11.1+5
  firebase_core: ^0.4.0+3
  auto_size_text: ^2.0.1
  intro_views_flutter:
  flutter_screenutil: ^0.5.2
  flutter_spinkit: ^3.1.0
  google_sign_in: ^4.0.2
  font_awesome_flutter: ^8.4.0
  flutter_rating: ^0.0.2
  flutter_fadein: ^1.1.1
  flutter_facebook_login:
    git:
      url: https://github.com/roughike/flutter_facebook_login
      ref: e69fef3
  http: ^0.12.0+2
  video_player: ^0.10.1+5
  chewie: ^0.9.7
  auto_orientation: ^0.0.2
  google_maps_flutter: ^0.5.19+2
  maps_launcher: ^1.0.0
  flare_flutter: ^1.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
    

    



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/cidades/
    - assets/porto_alegre/
    - assets/
    - assets/air-hostess.png
    - assets/airplane.png
    - assets/bus-driver.png
    - assets/bus.png
    - assets/hotel.png
    - assets/taxi.png
    - assets/taxi-driver.png
    - assets/waiter.png
    - assets/logoMarca.png
    - assets/porto_alegre/orla/
    - assets/porto_alegre/gremio/
    - assets/porto_alegre/inter/
    - assets/porto_alegre/santuario/
    - assets/porto_alegre/belem/
    - assets/porto_alegre/catedral/
    - assets/porto_alegre/ipanema/
    - assets/porto_alegre/botanico/
    - assets/porto_alegre/parque/
    - assets/porto_alegre/quintana/
    - assets/porto_alegre/mercado/
    - assets/porto_alegre/redencao/
    - assets/porto_alegre/marinha/
    - assets/porto_alegre/moinhos/
    - assets/gramado/
    - assets/gramado/lago/
    - assets/gramado/coberta/
    - assets/icons/
    - assets/lottie/
    - assets/iconPhone.png
    - assets/social/
    - assets/porto_alegre/
    #- assets/videos/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700

    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf

    - family: Fresca
      fonts:
        - asset: assets/fonts/Fresca-Regular.ttf

    - family: Lobster
      fonts:
        - asset: assets/fonts/Lobster-Regular.ttf

        

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
